c_compiler_version:    # [ppc64le]
- '7'                  # [ppc64le]
cxx_compiler_version:  # [ppc64le]
- '7'                  # [ppc64le]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
