{% set name = "fish" %}
{% set version = "2.7.0" %}
{% set sha256 = "3a76b7cae92f9f88863c35c832d2427fb66082f98e92a02203dc900b8fa87bcb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - ncurses 5.9*
  run:
    - ncurses 5.9*

test:
  commands:
    - fish --help
    - fish_indent --help

about:
  home: https://fishshell.com/
  license: GPL2
  license_file: COPYING
  summary: 'The user-friendly command line shell.'
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
