{% set name = "fish" %}
{% set version = "3.0.0" %}
{% set sha256 = "ea9dd3614bb0346829ce7319437c6a93e3e1dfde3b7f6a469b543b0d2c68f2cf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    - fish -v
    - fish_indent -v
    # - fish_key_reader -v  # returns 1 for any flag, so we can't really test it.

about:
  home: https://fishshell.com/
  license: GPL2
  license_file: COPYING
  summary: 'The user-friendly command line shell.'
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
