{% set name = "fish" %}
{% set version = "2.6.0" %}
{% set sha256 = "a12d3877eacb941e3212be323adbf396a80d9c1f843ddc94de427f3dfe81c7ad" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - gcc  # [linux]
    - toolchain  # [osx]
    - ncurses 5.9*
    - autoconf
    - automake
    - libtool
    - conda-build >=2.0
  run:
    - ncurses 5.9*

test:
  commands:
    - fish --help
    - fish_indent --help

about:
  home: https://fishshell.com/
  license: GPL2
  license_file: COPYING
  summary: 'The user-friendly command line shell.'
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
