{% set name = "fish" %}
{% set version = "2.5.0" %}
{% set sha256 = "03733fc4ec6dbdd10b3711ca5646436610d13ce0c3a14399787ab29471b2c24e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - gcc
    - ncurses 5.9*
    - autoconf
    - conda-build >=2.0
  run:
    - ncurses 5.9*

test:
  commands:
    - fish --help
    - fish_indent --help

about:
  home: https://fishshell.com/
  license: GPL2
  license_file: COPYING
  summary: 'The user-friendly command line shell.'
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
