context:
  version: "4.0.3"

package:
  name: fish
  version: ${{ version }}

source:
  url: https://github.com/fish-shell/fish-shell/archive/5346d3d491a4f2379b8f35869d810b396cd62526.zip
  sha256: c55079bd5e363dcd5f4e833136f8427c1279efc06909a63f40b6d86974750018
  target_directory: src

build:
  number: 1
  script: FISH_BUILD_VERSION=4.0.3 build.sh
  skip:
    - win

requirements:
  build:
    - cmake
    - make
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - gettext
    - git
  host:
    - ncurses
    - pcre2
    # For fish_run_tests
    - if: target_platform == "linux-64"
      then:
        - procps-ng
  run: []

tests:
  - script:
      - fish -v
      - fish_indent -v
  - script:
      - python ./tests/test_driver.py $CONDA_PREFIX/bin ./tests/pexpects/abbrs.py
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - pexpect
    files:
      recipe:
        - tests/

about:
  homepage: https://fishshell.com
  license: GPL-2.0-only
  license_file:
    - THIRDPARTY.yml
    - COPYING
  summary: User-friendly command-line shell for UNIX-like operating systems
  description: |
    Fish is a smart and user-friendly command line shell for macOS, Linux, and the rest of the family.
  repository: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - anjos
    - chrisburr
    - mdraw
