travis:
  secure:
    BINSTAR_TOKEN: NbkwwJxhGbiCsSxe3CH6JlQZfWFlwjkMiwecKeomYO8OMUt95Bkoh1pYLBkfc0XLm/c1/E+5EcAh8kEYmkbAmoFKnRK7D8i4/+sB+3rPFvnOfIGrpF00g1HdtGUfGTDfxe6V7CTldiMcBZVMuTPF6dU4lONJ/M54pztNoWLYP+vsPSEQSkojl1CeSgQ4oavPssoWMSbWQEzF7JnvW6bG5o4iSRjIq1HR+17l6viavl8EKcJL4gviyAkTMdNezD84fByXCvQWWuON43ACTqb1ENSI1XfXDKN7igpsxNUHY1/pjqGaw5eeu3YrCAV5kF1DJyt5C0Dk0aWxEqIfai2IU7RTJSBR9ce7bxcKd2zNnreXKuR9RSjxT7dOSUxL420OktirciME8CRTvnpdT1M76wVI93ri9j3HnCsWVsZxWXVg1bKBMegE/7lDDgxWQGaF4eFfr9LKvGNITx1u2UyjCyNOfaxhE3D6MXGXdmaV3ZsgDVAUDujuFtgNvgIJ4fUm2F1C/k2Lz3w/TatgKNJtGRFjLAutW3O9rhimWVK/vlHJphChjCcOiDzb1WCY3GJKyj2idrx8mWpSOHPXI9xB85goHQKVkZuWaiOjA/Lbg/gopDRyGPtagqmQgqozwPVGtrdacvXHLP92k1dutunEHRy+jz70Y1pcNxJAw1Bffu0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
