travis:
  secure:
    BINSTAR_TOKEN: VYoNFOJVd1cEIAm5x+bY19iIUxcoHnihqGx7giTofwuTVsQYLAko9t0CZ2gpllzBXwWkzkF2XeSuY3qoKodQLk1W4PNdF4P6bZqJjEBF6NEs+SnVHjvd7xv9KAFp/n2R4/uWZkHclfRfweYsl/b7T+aL/gXca4GRUKOTgCWN3AwtkAo2q1/WT6pQi3vdU2Wm1cT8JevO0I1vDx6v27SGddKOTxLG2QX2qOjsOYUl5XRDryFc6QGsdWOgBbaf3CZ/88y22DDXxgMjUtNbJl/QzefAk+4onYyXeMAunIcoJmffK7Cd8vJrLgY6lR1z56qaQ7SZwPXkZjBEpIGBzlcaGIsuSPzo6J/LGOfhJxIo7Bo3GjP2szh3s7BiIWRpe8LfaMhYDVrrko0L7s5CXUTKXplNLt/btISOKbOZXncL6m+OrD6GVx/LkiQVyWckpEv59mRCXIz2OHJf/Le16VtmNouE8LBjBUTeex6lcOS2A8UGvOU8uN1P6X5Oi98yhJxvTNtRLUlATR1uwgxOjiWDmTQmv0ria2MVUnK6l9jfLiTg/dSGpC2ZU3Jkybb+x+lNUrFMjSQMqBXYy1Y5Qw/Ik05y0rTfb+lcZ50bITLY73O29tzmPUl1e7L+EtCH6WUwG2AoEjOTg5Srxp0zGd15gzrWqOgzDXz1U37Bx1yaEkU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
