travis:
  secure:
    BINSTAR_TOKEN: gXmB+9Nn2cAGDXnjSR4m/jTkEfEMyxJM/2HR7XtViCPmRzpsrz2DVyIr15oPBv3HiBxo3hleEFpvpRaMhSvcCUb4NEmJa+Yq7yrmxEhBXfkUpkTyu5YKm0qYhkgyUHslFHxN5/eOsblSXDYaifz3XL+shJezVv9AjNU3xW/KsNpQCOroiTBhNVJJYBIwCQEfy5ViibqvjYTaVze0Iu46pN2nlA6Fo7Afb9A2XijKfcvxbuVz4anMWvYZadSLwU7hqZIT0iJI49OkCtQM4XAQwJBsZ5uvhl3/myTEQ8ksNTCBBADAuLycTvgZeVXRWsfrXUsgMaVqCQHQ+qXLSdbh168vqTAimziEkOv/Ltp3F/txLEXjfhNveeowPmiB0cvJc9m0lc+4xhUoBTTB4wuc8n/5CXZIyrhbzEi3YNUmOb4wokmkp5aq6QC9Rn3unPbJHaztOKG77q5UyoDjJdg1PUEEFSBoRnQYiFn7+uoG7lkc7lGa6QhqhClTC6JZjfhPlfr0Zxipu1vIMdvL4aSpTaE1vian7ZLQuJuAbS5dPtJVn26LawOUoee1N4em60nzEZMH+68F36VFg3Jv9tBEfRHp4V5Ab25km+fNHDYBzF98NNumhEpbVsCe4Uahihf3vCpd6EB1rFTJDsWdIzgQ8znP1b6L8+S7WH/iinawmZs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
